services:
  - type: web
    name: driveplay
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
